#!/bin/bash

######printing in shell script
echo 'Hello World'
##multiple line print
echo Hello1
echo Hello2
####using single echo cmd
echo Hello1\nHello2

####using opton e and use double quote
echo -e 'Hello1\nHello2'

##using tab 
echo -e '1.\tSmit\t\tVijay\n2.\tGood\t\tBoy'

##printing color
echo -e '\e[33myellow\e[0m'
echo -e 'No color'

##print both fg & bf
echo -e "\e[44;31mRED on BLUE\e[0m"
