#!/bin/bash

######printing in shell script
echo 'Hello World'
##multiple line print
echo Hello1
echo Hello2
####using single echo cmd
echo Hello1\nHello2

####using opton e and use double quote
echo -e 'Hello1\nHello2'

##using tab 

echo -e '1.\tSmit\tVijay\n2.\tGood\tBoy'
